import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Payload:
    "src/cms/payload/payload-types.ts",
    "src/app/(payload)/**",
    "src/cms/payload/migrations/**",
  ]),
  {
    // The site talks to the CMS only through @/content, so swapping CMS stays a
    // one-file change.
    files: ["src/app/(frontend)/**/*.{ts,tsx}", "src/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/cms/*", "@/cms/**"],
              message: "Import from @/content instead of reaching into the CMS adapter.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
