/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    experiences: Experience;
    expertise: Expertise;
    'skill-categories': SkillCategory;
    publications: Publication;
    photos: Photo;
    videos: Video;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    expertise: ExpertiseSelect<false> | ExpertiseSelect<true>;
    'skill-categories': SkillCategoriesSelect<false> | SkillCategoriesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
    navigation: Navigation;
    research: Research;
    trek: Trek;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    trek: TrekSelect<false> | TrekSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description: string;
  techStack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  githubUrl?: string | null;
  liveUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Add a row per other site this should appear on, with its position there (lower shows first). Leave empty to keep it on the main portfolio only.
   */
  placements?:
    | {
        site: 'research' | 'trek';
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  role: string;
  company: string;
  /**
   * Shown as written, e.g. "07/01/2024 - Current".
   */
  date: string;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Add a row per other site this should appear on, with its position there (lower shows first). Leave empty to keep it on the main portfolio only.
   */
  placements?:
    | {
        site: 'research' | 'trek';
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertise".
 */
export interface Expertise {
  id: number;
  domain: string;
  /**
   * e.g. "4+ Years"
   */
  years?: string | null;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Add a row per other site this should appear on, with its position there (lower shows first). Leave empty to keep it on the main portfolio only.
   */
  placements?:
    | {
        site: 'research' | 'trek';
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-categories".
 */
export interface SkillCategory {
  id: number;
  title: string;
  /**
   * Stable identifier, e.g. "web".
   */
  key: string;
  items?:
    | {
        name: string;
        rating: number;
        id?: string | null;
      }[]
    | null;
  show?: boolean | null;
  /**
   * 1 is highest priority.
   */
  priority: number;
  /**
   * Add a row per other site this should appear on, with its position there (lower shows first). Leave empty to keep it on the main portfolio only.
   */
  placements?:
    | {
        site: 'research' | 'trek';
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  authors: string;
  /**
   * e.g. "2024, September"
   */
  date: string;
  publisher: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Add a row per other site this should appear on, with its position there (lower shows first). Leave empty to keep it on the main portfolio only.
   */
  placements?:
    | {
        site: 'research' | 'trek';
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  /**
   * Shown under the photo and used as its alt text.
   */
  caption?: string | null;
  /**
   * Groups photos, e.g. "Everest Base Camp 2024".
   */
  album?: string | null;
  location?: string | null;
  /**
   * Which site these photos belong to.
   */
  site: 'research' | 'trek';
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * Any YouTube link: watch?v=…, youtu.be/… or /shorts/….
   */
  url: string;
  description?: string | null;
  /**
   * Optional grouping, e.g. a trek name.
   */
  album?: string | null;
  /**
   * Which site these films belong to.
   */
  site: 'research' | 'trek';
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'expertise';
        value: number | Expertise;
      } | null)
    | ({
        relationTo: 'skill-categories';
        value: number | SkillCategory;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  techStack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  githubUrl?: T;
  liveUrl?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  placements?:
    | T
    | {
        site?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  role?: T;
  company?: T;
  date?: T;
  description?: T;
  order?: T;
  placements?:
    | T
    | {
        site?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertise_select".
 */
export interface ExpertiseSelect<T extends boolean = true> {
  domain?: T;
  years?: T;
  description?: T;
  order?: T;
  placements?:
    | T
    | {
        site?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-categories_select".
 */
export interface SkillCategoriesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  items?:
    | T
    | {
        name?: T;
        rating?: T;
        id?: T;
      };
  show?: T;
  priority?: T;
  placements?:
    | T
    | {
        site?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  authors?: T;
  date?: T;
  publisher?: T;
  order?: T;
  placements?:
    | T
    | {
        site?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  caption?: T;
  album?: T;
  location?: T;
  site?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  description?: T;
  album?: T;
  site?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  name: string;
  headline: string;
  /**
   * Copy for the full-screen hero section.
   */
  hero: {
    title: string;
    /**
     * Joined in order into one paragraph (include spaces at the edges). Tick "highlight" to colour a segment.
     */
    description?:
      | {
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      href: string;
    };
  };
  /**
   * Absolute URL of the main portfolio, e.g. https://guptaamit.com.np — the other sites link back to it. A relative "/" would loop on a subdomain.
   */
  mainSiteUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  contact: {
    email: string;
    phone: string;
    location?: string | null;
    whatsapp?: string | null;
    linkedin?: string | null;
    github?: string | null;
    freelancer?: string | null;
    googleScholar?: string | null;
  };
  /**
   * Rendered as HTML, so inline tags like <strong> are allowed.
   */
  summary: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Each href must point at a section id on the home page, e.g. "/#about".
   */
  links?:
    | {
        name: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: number;
  title: string;
  tagline?: string | null;
  /**
   * Optional. Leave empty to reuse the main portfolio hero.
   */
  hero?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Rendered as HTML, so inline tags like <strong> are allowed. Research and coding focus.
   */
  about: string;
  /**
   * This site's own navigation. Hrefs are section ids on its page.
   */
  nav?:
    | {
        name: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to "<name> | <title>".
     */
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek".
 */
export interface Trek {
  id: number;
  title: string;
  tagline?: string | null;
  /**
   * Optional. Leave empty to reuse the main portfolio hero.
   */
  hero?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Rendered as HTML, so inline tags like <strong> are allowed. Trekking focus: routes, altitude, gear, what the walking is like.
   */
  about: string;
  /**
   * This site's own navigation. Hrefs are section ids on its page.
   */
  nav?:
    | {
        name: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to "<name> | <title>".
     */
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T;
  headline?: T;
  hero?:
    | T
    | {
        title?: T;
        description?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  mainSiteUrl?: T;
  image?: T;
  imageUrl?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        location?: T;
        whatsapp?: T;
        linkedin?: T;
        github?: T;
        freelancer?: T;
        googleScholar?: T;
      };
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  about?: T;
  nav?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek_select".
 */
export interface TrekSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  about?: T;
  nav?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}