/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'tech-experiences': TechExperience;
    'tech-skill-categories': TechSkillCategory;
    'tech-expertise': TechExpertise;
    'tech-projects': TechProject;
    'tech-publications': TechPublication;
    'tech-photos': TechPhoto;
    'tech-videos': TechVideo;
    'research-experiences': ResearchExperience;
    'research-skill-categories': ResearchSkillCategory;
    'research-expertise': ResearchExpertise;
    'research-projects': ResearchProject;
    'research-publications': ResearchPublication;
    'research-photos': ResearchPhoto;
    'research-videos': ResearchVideo;
    'trek-experiences': TrekExperience;
    'trek-skill-categories': TrekSkillCategory;
    'trek-expertise': TrekExpertise;
    'trek-projects': TrekProject;
    'trek-publications': TrekPublication;
    'trek-photos': TrekPhoto;
    'trek-videos': TrekVideo;
    'trek-treks': TrekTrek;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'tech-experiences': TechExperiencesSelect<false> | TechExperiencesSelect<true>;
    'tech-skill-categories': TechSkillCategoriesSelect<false> | TechSkillCategoriesSelect<true>;
    'tech-expertise': TechExpertiseSelect<false> | TechExpertiseSelect<true>;
    'tech-projects': TechProjectsSelect<false> | TechProjectsSelect<true>;
    'tech-publications': TechPublicationsSelect<false> | TechPublicationsSelect<true>;
    'tech-photos': TechPhotosSelect<false> | TechPhotosSelect<true>;
    'tech-videos': TechVideosSelect<false> | TechVideosSelect<true>;
    'research-experiences': ResearchExperiencesSelect<false> | ResearchExperiencesSelect<true>;
    'research-skill-categories': ResearchSkillCategoriesSelect<false> | ResearchSkillCategoriesSelect<true>;
    'research-expertise': ResearchExpertiseSelect<false> | ResearchExpertiseSelect<true>;
    'research-projects': ResearchProjectsSelect<false> | ResearchProjectsSelect<true>;
    'research-publications': ResearchPublicationsSelect<false> | ResearchPublicationsSelect<true>;
    'research-photos': ResearchPhotosSelect<false> | ResearchPhotosSelect<true>;
    'research-videos': ResearchVideosSelect<false> | ResearchVideosSelect<true>;
    'trek-experiences': TrekExperiencesSelect<false> | TrekExperiencesSelect<true>;
    'trek-skill-categories': TrekSkillCategoriesSelect<false> | TrekSkillCategoriesSelect<true>;
    'trek-expertise': TrekExpertiseSelect<false> | TrekExpertiseSelect<true>;
    'trek-projects': TrekProjectsSelect<false> | TrekProjectsSelect<true>;
    'trek-publications': TrekPublicationsSelect<false> | TrekPublicationsSelect<true>;
    'trek-photos': TrekPhotosSelect<false> | TrekPhotosSelect<true>;
    'trek-videos': TrekVideosSelect<false> | TrekVideosSelect<true>;
    'trek-treks': TrekTreksSelect<false> | TrekTreksSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    tech: Tech;
    research: Research;
    trek: Trek;
  };
  globalsSelect: {
    tech: TechSelect<false> | TechSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    trek: TrekSelect<false> | TrekSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-experiences".
 */
export interface TechExperience {
  id: number;
  role: string;
  company: string;
  /**
   * Shown as written, e.g. "07/01/2024 - Current".
   */
  date: string;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-skill-categories".
 */
export interface TechSkillCategory {
  id: number;
  title: string;
  /**
   * Stable identifier, e.g. "web".
   */
  key: string;
  items?:
    | {
        name: string;
        rating: number;
        id?: string | null;
      }[]
    | null;
  show?: boolean | null;
  /**
   * 1 is highest priority.
   */
  priority: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-expertise".
 */
export interface TechExpertise {
  id: number;
  domain: string;
  /**
   * e.g. "4+ Years"
   */
  years?: string | null;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-projects".
 */
export interface TechProject {
  id: number;
  title: string;
  description: string;
  techStack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  githubUrl?: string | null;
  liveUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-publications".
 */
export interface TechPublication {
  id: number;
  title: string;
  authors: string;
  /**
   * e.g. "2024, September"
   */
  date: string;
  publisher: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-photos".
 */
export interface TechPhoto {
  id: number;
  /**
   * Shown under the photo and used as its alt text.
   */
  caption?: string | null;
  /**
   * Groups photos, e.g. "Everest Base Camp 2024".
   */
  album?: string | null;
  location?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-videos".
 */
export interface TechVideo {
  id: number;
  title: string;
  /**
   * Any YouTube link: watch?v=…, youtu.be/… or /shorts/….
   */
  url: string;
  description?: string | null;
  /**
   * Optional grouping, e.g. a trek name.
   */
  album?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-experiences".
 */
export interface ResearchExperience {
  id: number;
  role: string;
  company: string;
  /**
   * Shown as written, e.g. "07/01/2024 - Current".
   */
  date: string;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-skill-categories".
 */
export interface ResearchSkillCategory {
  id: number;
  title: string;
  /**
   * Stable identifier, e.g. "web".
   */
  key: string;
  items?:
    | {
        name: string;
        rating: number;
        id?: string | null;
      }[]
    | null;
  show?: boolean | null;
  /**
   * 1 is highest priority.
   */
  priority: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-expertise".
 */
export interface ResearchExpertise {
  id: number;
  domain: string;
  /**
   * e.g. "4+ Years"
   */
  years?: string | null;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-projects".
 */
export interface ResearchProject {
  id: number;
  title: string;
  description: string;
  techStack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  githubUrl?: string | null;
  liveUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-publications".
 */
export interface ResearchPublication {
  id: number;
  title: string;
  authors: string;
  /**
   * e.g. "2024, September"
   */
  date: string;
  publisher: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-photos".
 */
export interface ResearchPhoto {
  id: number;
  /**
   * Shown under the photo and used as its alt text.
   */
  caption?: string | null;
  /**
   * Groups photos, e.g. "Everest Base Camp 2024".
   */
  album?: string | null;
  location?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-videos".
 */
export interface ResearchVideo {
  id: number;
  title: string;
  /**
   * Any YouTube link: watch?v=…, youtu.be/… or /shorts/….
   */
  url: string;
  description?: string | null;
  /**
   * Optional grouping, e.g. a trek name.
   */
  album?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-experiences".
 */
export interface TrekExperience {
  id: number;
  role: string;
  company: string;
  /**
   * Shown as written, e.g. "07/01/2024 - Current".
   */
  date: string;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-skill-categories".
 */
export interface TrekSkillCategory {
  id: number;
  title: string;
  /**
   * Stable identifier, e.g. "web".
   */
  key: string;
  items?:
    | {
        name: string;
        rating: number;
        id?: string | null;
      }[]
    | null;
  show?: boolean | null;
  /**
   * 1 is highest priority.
   */
  priority: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-expertise".
 */
export interface TrekExpertise {
  id: number;
  domain: string;
  /**
   * e.g. "4+ Years"
   */
  years?: string | null;
  description: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-projects".
 */
export interface TrekProject {
  id: number;
  title: string;
  description: string;
  techStack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  githubUrl?: string | null;
  liveUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-publications".
 */
export interface TrekPublication {
  id: number;
  title: string;
  authors: string;
  /**
   * e.g. "2024, September"
   */
  date: string;
  publisher: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-photos".
 */
export interface TrekPhoto {
  id: number;
  /**
   * Shown under the photo and used as its alt text.
   */
  caption?: string | null;
  /**
   * Groups photos, e.g. "Everest Base Camp 2024".
   */
  album?: string | null;
  location?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-videos".
 */
export interface TrekVideo {
  id: number;
  title: string;
  /**
   * Any YouTube link: watch?v=…, youtu.be/… or /shorts/….
   */
  url: string;
  description?: string | null;
  /**
   * Optional grouping, e.g. a trek name.
   */
  album?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-treks".
 */
export interface TrekTrek {
  id: number;
  title: string;
  /**
   * URL segment, e.g. "everest-base-camp" → /trek/everest-base-camp.
   */
  slug: string;
  /**
   * e.g. "Khumbu, Nepal"
   */
  region?: string | null;
  /**
   * e.g. "Mar–May, Sep–Nov"
   */
  season?: string | null;
  /**
   * Typical days on the trail.
   */
  days?: number | null;
  maxAltitudeM?: number | null;
  distanceKm?: number | null;
  /**
   * One or two lines, shown on the cards.
   */
  summary: string;
  /**
   * Your account of the trek. Rendered as HTML; leave empty to show only the summary.
   */
  body?: string | null;
  heroImage?: (number | null) | TrekPhoto;
  /**
   * Photos shown on this trek's page.
   */
  gallery?: (number | TrekPhoto)[] | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tech-experiences';
        value: number | TechExperience;
      } | null)
    | ({
        relationTo: 'tech-skill-categories';
        value: number | TechSkillCategory;
      } | null)
    | ({
        relationTo: 'tech-expertise';
        value: number | TechExpertise;
      } | null)
    | ({
        relationTo: 'tech-projects';
        value: number | TechProject;
      } | null)
    | ({
        relationTo: 'tech-publications';
        value: number | TechPublication;
      } | null)
    | ({
        relationTo: 'tech-photos';
        value: number | TechPhoto;
      } | null)
    | ({
        relationTo: 'tech-videos';
        value: number | TechVideo;
      } | null)
    | ({
        relationTo: 'research-experiences';
        value: number | ResearchExperience;
      } | null)
    | ({
        relationTo: 'research-skill-categories';
        value: number | ResearchSkillCategory;
      } | null)
    | ({
        relationTo: 'research-expertise';
        value: number | ResearchExpertise;
      } | null)
    | ({
        relationTo: 'research-projects';
        value: number | ResearchProject;
      } | null)
    | ({
        relationTo: 'research-publications';
        value: number | ResearchPublication;
      } | null)
    | ({
        relationTo: 'research-photos';
        value: number | ResearchPhoto;
      } | null)
    | ({
        relationTo: 'research-videos';
        value: number | ResearchVideo;
      } | null)
    | ({
        relationTo: 'trek-experiences';
        value: number | TrekExperience;
      } | null)
    | ({
        relationTo: 'trek-skill-categories';
        value: number | TrekSkillCategory;
      } | null)
    | ({
        relationTo: 'trek-expertise';
        value: number | TrekExpertise;
      } | null)
    | ({
        relationTo: 'trek-projects';
        value: number | TrekProject;
      } | null)
    | ({
        relationTo: 'trek-publications';
        value: number | TrekPublication;
      } | null)
    | ({
        relationTo: 'trek-photos';
        value: number | TrekPhoto;
      } | null)
    | ({
        relationTo: 'trek-videos';
        value: number | TrekVideo;
      } | null)
    | ({
        relationTo: 'trek-treks';
        value: number | TrekTrek;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-experiences_select".
 */
export interface TechExperiencesSelect<T extends boolean = true> {
  role?: T;
  company?: T;
  date?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-skill-categories_select".
 */
export interface TechSkillCategoriesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  items?:
    | T
    | {
        name?: T;
        rating?: T;
        id?: T;
      };
  show?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-expertise_select".
 */
export interface TechExpertiseSelect<T extends boolean = true> {
  domain?: T;
  years?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-projects_select".
 */
export interface TechProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  techStack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  githubUrl?: T;
  liveUrl?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-publications_select".
 */
export interface TechPublicationsSelect<T extends boolean = true> {
  title?: T;
  authors?: T;
  date?: T;
  publisher?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-photos_select".
 */
export interface TechPhotosSelect<T extends boolean = true> {
  caption?: T;
  album?: T;
  location?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-videos_select".
 */
export interface TechVideosSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  description?: T;
  album?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-experiences_select".
 */
export interface ResearchExperiencesSelect<T extends boolean = true> {
  role?: T;
  company?: T;
  date?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-skill-categories_select".
 */
export interface ResearchSkillCategoriesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  items?:
    | T
    | {
        name?: T;
        rating?: T;
        id?: T;
      };
  show?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-expertise_select".
 */
export interface ResearchExpertiseSelect<T extends boolean = true> {
  domain?: T;
  years?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-projects_select".
 */
export interface ResearchProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  techStack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  githubUrl?: T;
  liveUrl?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-publications_select".
 */
export interface ResearchPublicationsSelect<T extends boolean = true> {
  title?: T;
  authors?: T;
  date?: T;
  publisher?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-photos_select".
 */
export interface ResearchPhotosSelect<T extends boolean = true> {
  caption?: T;
  album?: T;
  location?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-videos_select".
 */
export interface ResearchVideosSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  description?: T;
  album?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-experiences_select".
 */
export interface TrekExperiencesSelect<T extends boolean = true> {
  role?: T;
  company?: T;
  date?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-skill-categories_select".
 */
export interface TrekSkillCategoriesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  items?:
    | T
    | {
        name?: T;
        rating?: T;
        id?: T;
      };
  show?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-expertise_select".
 */
export interface TrekExpertiseSelect<T extends boolean = true> {
  domain?: T;
  years?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-projects_select".
 */
export interface TrekProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  techStack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  githubUrl?: T;
  liveUrl?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-publications_select".
 */
export interface TrekPublicationsSelect<T extends boolean = true> {
  title?: T;
  authors?: T;
  date?: T;
  publisher?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-photos_select".
 */
export interface TrekPhotosSelect<T extends boolean = true> {
  caption?: T;
  album?: T;
  location?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-videos_select".
 */
export interface TrekVideosSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  description?: T;
  album?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek-treks_select".
 */
export interface TrekTreksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  region?: T;
  season?: T;
  days?: T;
  maxAltitudeM?: T;
  distanceKm?: T;
  summary?: T;
  body?: T;
  heroImage?: T;
  gallery?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech".
 */
export interface Tech {
  id: number;
  title: string;
  tagline?: string | null;
  name: string;
  headline: string;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  /**
   * Absolute URL of the main portfolio, e.g. https://guptaamit.com.np — other sites link back to it. A relative "/" would loop on a subdomain.
   */
  mainSiteUrl?: string | null;
  contact: {
    email: string;
    phone: string;
    location?: string | null;
    whatsapp?: string | null;
    linkedin?: string | null;
    github?: string | null;
    freelancer?: string | null;
    googleScholar?: string | null;
  };
  /**
   * About copy for this site. Rendered as HTML.
   */
  summary: string;
  /**
   * This site's full-screen hero.
   */
  hero: {
    title: string;
    /**
     * Joined in order into one paragraph (include spaces at the edges). Tick "highlight" to colour a segment.
     */
    description?:
      | {
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      href: string;
    };
  };
  /**
   * This site's own navigation; hrefs are section ids on its page.
   */
  nav?:
    | {
        name: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to "<name> | <title>".
     */
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: number;
  title: string;
  tagline?: string | null;
  name: string;
  headline: string;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  /**
   * Absolute URL of the main portfolio, e.g. https://guptaamit.com.np — other sites link back to it. A relative "/" would loop on a subdomain.
   */
  mainSiteUrl?: string | null;
  contact: {
    email: string;
    phone: string;
    location?: string | null;
    whatsapp?: string | null;
    linkedin?: string | null;
    github?: string | null;
    freelancer?: string | null;
    googleScholar?: string | null;
  };
  /**
   * About copy for this site. Rendered as HTML.
   */
  summary: string;
  /**
   * This site's full-screen hero.
   */
  hero: {
    title: string;
    /**
     * Joined in order into one paragraph (include spaces at the edges). Tick "highlight" to colour a segment.
     */
    description?:
      | {
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      href: string;
    };
  };
  /**
   * This site's own navigation; hrefs are section ids on its page.
   */
  nav?:
    | {
        name: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to "<name> | <title>".
     */
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek".
 */
export interface Trek {
  id: number;
  title: string;
  tagline?: string | null;
  name: string;
  headline: string;
  image?: (number | null) | Media;
  /**
   * Used when no image is uploaded.
   */
  imageUrl?: string | null;
  /**
   * Absolute URL of the main portfolio, e.g. https://guptaamit.com.np — other sites link back to it. A relative "/" would loop on a subdomain.
   */
  mainSiteUrl?: string | null;
  contact: {
    email: string;
    phone: string;
    location?: string | null;
    whatsapp?: string | null;
    linkedin?: string | null;
    github?: string | null;
    freelancer?: string | null;
    googleScholar?: string | null;
  };
  /**
   * About copy for this site. Rendered as HTML.
   */
  summary: string;
  /**
   * This site's full-screen hero.
   */
  hero: {
    title: string;
    /**
     * Joined in order into one paragraph (include spaces at the edges). Tick "highlight" to colour a segment.
     */
    description?:
      | {
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      href: string;
    };
  };
  /**
   * This site's own navigation; hrefs are section ids on its page.
   */
  nav?:
    | {
        name: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to "<name> | <title>".
     */
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech_select".
 */
export interface TechSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  name?: T;
  headline?: T;
  image?: T;
  imageUrl?: T;
  mainSiteUrl?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        location?: T;
        whatsapp?: T;
        linkedin?: T;
        github?: T;
        freelancer?: T;
        googleScholar?: T;
      };
  summary?: T;
  hero?:
    | T
    | {
        title?: T;
        description?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  nav?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  name?: T;
  headline?: T;
  image?: T;
  imageUrl?: T;
  mainSiteUrl?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        location?: T;
        whatsapp?: T;
        linkedin?: T;
        github?: T;
        freelancer?: T;
        googleScholar?: T;
      };
  summary?: T;
  hero?:
    | T
    | {
        title?: T;
        description?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  nav?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trek_select".
 */
export interface TrekSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  name?: T;
  headline?: T;
  image?: T;
  imageUrl?: T;
  mainSiteUrl?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        location?: T;
        whatsapp?: T;
        linkedin?: T;
        github?: T;
        freelancer?: T;
        googleScholar?: T;
      };
  summary?: T;
  hero?:
    | T
    | {
        title?: T;
        description?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  nav?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}